name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: fast-feet

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - run: npm ci

      - run: npm run test:e2e
        env:
          - DATABASE_URL: ${{secrets.DATABASE_URL}}
          - JWT_PRIVATE_KEY: ${{secrets.JWT_PRIVATE_KEY}}
          - JWT_PUBLIC_KEY: ${{secrets.JWT_PUBLIC_KEY}}
          - CLOUDFLARE_ACCOUNT_ID: ${{secrets.CLOUDFLARE_ACCOUNT_ID}}
          - AWS_BUCKET_NAME: ${{secrets.AWS_BUCKET_NAME}}
          - AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          - AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
